### ISSUE TITLE
npm install deepify -g on windows

### ISSUE THREAD

**Issue by PaulStAmand** [MitocGroup/deep-framework#247]
I first tried upgrading node using the binary installer, which given the error I didnt think would resolv the problem.

I have npm 3.6.0 and node .7.0 installed
I get to preinstall and it appears the installer is calling a bash script rather than rely only on node.

It get the following err:
c:\Users\user>npm install deepify -g
I get to the npm run compile

fail will occur on windows when
>bash node-bin/compile.sh is reached as that's not std on windows

I see mention searching around on relying node to help with cross platform.

Am I the 1st to try instslling on windows?

**Comment by eistrati** [comment]
@PaulStAmand Thank you for reporting this issue. I was wondering if you could follow below steps and let us know if it still works for you: https://github.com/MitocGroup/deep-microservices-todo-app/blob/master/src/DeepNgToDo/Docs/index.md

**Comment by PaulStAmand** [comment]
Certainly, soon as I get off this conference call.

**Comment by eistrati** [comment]
Again, thank you for reporting this issue! We acknowledge that it's not properly documented, therefore we have updated the [README.md](https://github.com/MitocGroup/deep-framework/blob/master/README.md#getting-started-) file as follows:

_Note: If you want to use `deepify` on Windows, please follow the steps from [Windows Configuration](https://github.com/MitocGroup/deep-framework/blob/master/docs/windows.md) before running `npm install deepify -g` and make sure all `npm` and `deepify` commands are executed inside Git Bash._

**Comment by PaulStAmand** [comment]
Hello,

I had git installed but bash wasnt in my path.  I upgraded and ran npm
install deepify again and same failure.  For some reason bash still isn't a
part of the path after installing git 2.7.2.windows.1

Looking over the git install process to ensure I didnt mistype something.

**Comment by PaulStAmand** [comment]
ok the git installer puts program files\Git\cmd into the path but bash and
sh aren't located in that folder.  That appears to be a git installer
issue.  The installer does put those files in program files\git\bin , but
that's not added to the path.  I copied bash and sh binaries to the git\cmd
folder.

I got further:

C:\Users\user>npm install deepify -g

> deepify@1.6.15 preinstall C:\Users\user\AppData\Roaming\npm\node_modules\.
staging\deepify-d1fa4c95
> npm run compile


> deepify@1.6.15 compile C:\Users\user\AppData\Roaming\npm\node_modules\.sta
ging\deepify-d1fa4c95
> bash node-bin/compile.sh

C:\Users\user\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "deepify" "-g"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\deepify
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename
'C:\Users\user\AppData\Roaming\npm\node_modules\deepify' ->
'C:\Users\user\AppData\Roaming\npm\node_modules\.deepify.DELETE'
npm ERR!     at moveAway (C:\Program
Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program
Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename
'C:\Users\user\AppData\Roaming\npm\node_modules\deepify' ->
'C:\Users\user\AppData\Roaming\npm\node_modules\.deepify.DELETE'
npm ERR!     at Error (native)
npm ERR!  [Error: EPERM: operation not permitted, rename
'C:\Users\user\AppData\Roaming\npm\node_modules\deepify' ->
'C:\Users\user\AppData\Roaming\npm\node_modules\.deepify.DELETE']
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log
npm ERR! code 1

C:\Users\user>

**Comment by eistrati** [comment]
To be honest, it worked for us on machines using default Windows. I think your version of Windows is customized for better security (to be read as more restrictions)...

To the point, It looks like `npm` requires Administrator privileges. Did you try to launch Git Bash as Admin? Meanwhile we'll try to update the docs and point this out as well.

**Comment by PaulStAmand** [comment]
still the same.  I see other references to similar errors.

Some resolved it by temporarily disabling AntiVirus
I can't disable my AV

for some people on other packages npm cache clean worked
I've tried it and also adding --force

as a user and also as admin

running npm install deepify -g is running again as user

same errors

now running from git bash as admin

Still getting not permitted on the rename as admin from git bash

**Comment by PaulStAmand** [comment]
Its apparently a windows specific bug within npm that doesnt have a clear
fix.  I'm on an older machine and that seems to cause more trouble.

https://github.com/npm/npm/issues/9696

hopefully this works well on my other machine.

clearing the npm cache didnt help, but I'm not alone with this error, not
sure if there are ways for packages to minimize the potential impact of
this npm bug on windows.

 --force even after a complete removal of node and all the modules and
reinstall did nothing.

**Comment by eistrati** [comment]
@PaulStAmand Thanks for extensive research! We'll try to incorporate your feedback into our project as much as possible, but since we're primarily dependent on node and npm, we're limited in resources that can address them effectively. We'll keep this issue open and keep an eye on https://github.com/npm/npm/issues/9696

As an alternative, could you please try to use node4-lts instead? It worked for us and hopefully it will work for you. Really curious to learn your experience, if you see the same issue or not.

**Comment by PaulStAmand** [comment]
Under windows 10, also a faster machine, it worked with git-bash installed
from both git-bash and also from cmd with node 0.12 from last year and also
with node 4.3.1
I had to copy bash and sh to the git\cmd folder for the deepify to install
from cmd.  the install ran fine from git-bash either way.

**Comment by PaulStAmand** [comment]
I've uninstalled nodejs 5.7.1 from the windows 7 machine and installed
4.3.1LTS and running through deepify install from a git bash shell.

success.

deepify installed without any complaints from node 4.3.1 LTS, all from 64
bit node binary installs

**Comment by PaulStAmand** [comment]
slowly making progress

on windows deepify helloworld ~/deep-hello-world result in the home
directory ~ folder and then within it the expected folder being created

I'm trying to dig through why server looks for the AWS access keys and
seems to target us-west-1 regardless

**Comment by PaulStAmand** [comment]
I started with deep-todo-app, helloworld aside from the ~/ might be working

**Comment by eistrati** [comment]
This is great news. Yes, ~ points to home in Unix-like environment. We'll have to make a notice for Windows-specific environments. Thank you and I'll keep this issue open, to be able to communicate when `npm` or `deepify` will solve the (eaerlier) above described issues.

**Comment by PaulStAmand** [comment]
Is there a way to enable verbose debugging...  deepify server
deep-hello-world seems to be stuck under windows 10

**Comment by eistrati** [comment]
Unfortunately, at this moment, `deepify` doesn't support verbose debugging mode. One work-around that comes into my mind is to change `npm` to another loglevel, let's say for example: `npm config set loglevel verbose`

**Comment by eistrati** [comment]
To answer an earlier question regarding aws keys for `deepify server`: We are using locally simulated AWS services like Lambda and Dynamodb. Because aws-sdk requires keys anyway, `deepify` looks in places like `~/.aws/config` or environmental variables to store them in the (micro)application's `deeploy.json`. If the keys are not detected, default values are used instead.

**Comment by PaulStAmand** [comment]
on the windows 10 machine nothing displays after hitting enter.

I may have to launch sysinternals to see what the process is doing.

**Comment by eistrati** [comment]
By the way, please keep updating to the latest version of `deepify` (e.g. `npm install deepify -g`). We are incorporating your feedback and publishing fixes to it, so further feedback on improvements is always appreciated.

**Comment by PaulStAmand** [comment]
I tried running from cmd instead of git-bash and rather than just sitting
there I'm prompted for AWS credentials:

but I get:

C:\Users\user>deepify server deep-hello-world -o
13:36:04 GMT-0500 (Eastern Standard Time)  { [ValidationError: child "aws"
fails because [child "accessKeyId" fails because ["accessKeyId" is not
allowed to be empty]]]
  name: 'ValidationError',
  details:
   [ { message: '"accessKeyId" is not allowed to be empty',
       path: 'aws.accessKeyId',
       type: 'any.empty',
       context: [Object] } ],
  _object:
   { appIdentifier: 'unique-app-id-1456596859557',
     env: 'dev',
     awsAccountId: 123456789012,
     aws: { accessKeyId: '', secretAccessKey: '', region: 'us-east-1' } },
  annotate: [Function] }
13:36:04 GMT-0500 (Eastern Standard Time)  b: ValidationError: child "aws"
fails because [child "accessKeyId" fails because ["accessKeyId" is not
allowed to be empty]]
    at a._createClass.value
(C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-package-manager\lib.compiled\Property\Config.js:1:1191)
    at new a
(C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-package-manager\lib.compiled\Property\Instance.js:1:2834)
    at a.module.exports [as _action]
(C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\commands\server.js:53:18)
    at a._createClass.value
(C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Terminal\Program.js:1:4205)
    at a._createClass.value
(C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Terminal\Program.js:1:3959)
    at Object.<anonymous>
(C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\deepify.js:56:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by eistrati** [comment]
Thank you! This helps a lot. We have recently discovered this bug as well, and will prioritize it.

In summary, instead of using empty values, we'll put placeholders like YOUR_AWS_ACCES_KEY and YOUR_AWS_SECRET_KEY, as well as prompt interactive questions to ask for AWS keys at both `deepify server` and `deepify deploy` steps.

For internal reference: https://github.com/MitocGroup/deepify/issues/117

**Comment by eistrati** [comment]
@PaulStAmand AWS keys issue was fixed, but we have identified another issue that might still block you from using `deepify` on Windows:

https://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows

We're working on fixing this as well, and I'll report back when we'll get the fix in place.

**Comment by PaulStAmand** [comment]
Its unreal this path length limitation still exists within windows.  I've
been bitten before by this one.

**Comment by PaulStAmand** [comment]
this might be some of the windows functions not being re-entrant

C:\Users\pstamand>npm install deepify -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "deepify" "-g"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\pstamand\AppData\Roaming\npm\node_modules\deepify\bin\com
mands
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\pstamand\AppData\Roamin
g\npm\node_modules\deepify\bin\commands'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, rmdir 'C:\Use
rs\pstamand\AppData\Roaming\npm\node_modules\deepify\bin\commands'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'C:
\Users\pstamand\AppData\Roaming\npm\node_modules\deepify\bin\commands']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: 'C:\\Users\\pstamand\\AppData\\Roaming\\npm\
\node_modules\\deepify\\bin\\commands' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pstamand\npm-debug.log

I can't disable anything on this windows 7 machine to see if its AV or active threat scanning related.  I'll try it from the windows 10 machine later.

I tried this from both user and admin.

**Comment by eistrati** [comment]
Thanks, @PaulStAmand. We have updated [README.md](https://github.com/MitocGroup/deep-framework/blob/master/README.md) with the following note:

*Note: If you want to use deepify on Windows, please follow the steps from [Windows Configuration](https://github.com/MitocGroup/deep-framework/blob/master/docs/windows.md) before running `npm install deepify -g` and make sure all `npm` and `deepify` commands are executed inside Git Bash.*

Can you please retry the same steps in Git Bash and let me know if above issues are replicated?

**Comment by PaulStAmand** [comment]
Same results

user@user-3 MINGW64 ~
$ npm install deepify -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "deepify" "-g"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\com
mands
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\user\AppData\Roamin
g\npm\node_modules\deepify\bin\commands'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, rmdir 'C:\Use
rs\user\AppData\Roaming\npm\node_modules\deepify\bin\commands'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'C:
\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\commands']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: 'C:\\Users\\user\\AppData\\Roaming\\npm\
\node_modules\\deepify\\bin\\commands' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

user@user-3 MINGW64 ~
$

**Comment by eistrati** [comment]
Ok, this is super helpful. Thanks a lot! Our team is trying to replicate and figure out a fix for it.

And thank you for your patience. Windows is a pain to support, but with your help I hope we'll get it there.

**Comment by PaulStAmand** [comment]
This appears to be an unresolved NPM issue that on windows keeps popping up.

**Comment by PaulStAmand** [comment]
On the windows 10 machine with AVG from git-bash
npm install deepfy -g completes

$ npm install deepify -g

> deepify@1.7.3 preinstall C:\Users\user\AppData\Roaming\npm\node_modules\deepify
> npm run compile


> deepify@1.7.3 compile C:\Users\user\AppData\Roaming\npm\node_modules\deepify
> bash node-bin/compile.sh

Skipping code transpiling to ES5...

> dtrace-provider@0.6.0 install C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-db\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js


> dtrace-provider@0.6.0 install C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-db\node_modules\deep-validation\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js


> leveldown@1.4.4 install C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-db\node_modules\dynalite\node_modules\leveldown
> prebuild --install

C:\Users\user\AppData\Roaming\npm\deepify -> C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\deepify.js

> deepify@1.7.3 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\deepify
> bash hooks/autocomplete_deepify.sh

Completion setup in /c/Users/user/.bashrc, skipping...
deepify@1.7.3 C:\Users\user\AppData\Roaming\npm\node_modules\deepify
├── jsonfile@1.2.0
├── open@0.0.5
├── mime@1.3.4
├── tmp@0.0.28 (os-tmpdir@1.0.1)
├── deep-core@1.7.1 (qs@5.2.0)
├── proxyquire@1.7.4 (module-not-found-error@1.0.1, fill-keys@1.0.2)
├── fs-extra@0.23.1 (path-is-absolute@1.0.0, jsonfile@2.2.3, graceful-fs@4.1.3, rimraf@2.5.2)
├── aws-api-gw-client@0.1.17 (es6-promise@3.0.2, stackable-fetcher-aws-signer-v4@0.0.1, stackable-fetcher@0.3.0)
├── gather-dependencies@1.0.0 (read-package-tree@5.1.2)
├── deep-fs@1.7.1 (relative-fs@0.0.1, es6-promise@3.1.2, deep-kernel@1.7.0, s3fs@2.4.0, fs-extra@0.26.5)
├── deep-log@1.7.0 (raven@0.7.3, deep-kernel@1.7.0, joi@5.1.0)
├── aws-sdk@2.2.40 (sax@1.1.5, xml2js@0.4.15, xmlbuilder@2.6.2)
├── deep-package-manager@1.7.3 (ignore@2.2.19, css-find-assets@0.0.3, graceful-fs@4.1.3, string2stream@0.0.2, spawn-cmd@0.0.2, raml-validate@1.0.6, raml-sanitize@1.1.2, crypto@0.0.3, readline-sync@1.4.1, crc@3.4.0, semver@5.1.0, sync-exec@0.6.2, json-pointer@0.3.1, mkdirp@0.5.1, tar-stream@1.3.2, object-merge@2.5.1, joi@6.10.1, css-parse@2.0.0, gunzip-maybe@1.3.1, fstream@1.0.8, moment@2.11.2, find-assets@0.3.1, archiver@0.14.4, fetchy-request@0.8.7)
└── deep-db@1.7.0 (deep-kernel@1.7.0, fs-extra@0.26.5, joi@5.1.0, vogels@2.2.0, local-dynamo@0.1.2, deep-validation@1.7.0, dynalite@0.17.3)

**Comment by PaulStAmand** [comment]
Should this work on windows with 1.7.3...  

user@toshiba MINGW64 ~
$ deepify server deep-hello-world -o
15:42:14 GMT-0500 (Eastern Standard Time)  { [ValidationError: child "aws" fails because [child "accessKeyId" fails because ["accessKeyId" is not allowed to be empty]]]
  name: 'ValidationError',
  details:
   [ { message: '"accessKeyId" is not allowed to be empty',
       path: 'aws.accessKeyId',
       type: 'any.empty',
       context: [Object] } ],
  _object:
   { appIdentifier: 'unique-app-id-1456596859557',
     env: 'dev',
     awsAccountId: 123456789012,
     aws: { accessKeyId: '', secretAccessKey: '', region: 'us-east-1' } },
  annotate: [Function] }
15:42:14 GMT-0500 (Eastern Standard Time)  b: ValidationError: child "aws" fails because [child "accessKeyId" fails because ["accessKeyId" is not allowed to be empty]]
    at a._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-package-manager\lib.compiled\Property\Config.js:1:1191)
    at new a (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-package-manager\lib.compiled\Property\Instance.js:1:2834)
    at a.module.exports [as _action] (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\commands\server.js:53:18)
    at a._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Terminal\Program.js:1:4223)
    at a._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Terminal\Program.js:1:3977)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\deepify.js:56:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

user@toshiba MINGW64 ~
$

**Comment by eistrati** [comment]
@PaulStAmand We were able to reproduce this issue again and working now to add more check points in place. Regarding the earlier issue with `code EBUSY errno -4082`, it looks like this is a known issue and we'll keep monitoring it as well: https://github.com/npm/npm/issues/7370 (somebody suggests reboot, and at this point nothing impresses me:)

**Comment by eistrati** [comment]
@PaulStAmand Here below is some more info we've learned recently:

*When `symlink` is used in Windows, the script should have admin rights because the default security policy allows only administrators to create symbolic links: https://github.com/nodejs/node-v0.x-archive/issues/6342*

We'll update [Windows Configuration](https://github.com/MitocGroup/deep-framework/blob/master/docs/windows.md) doc to reflect this requirement with explanations. Therefore, going forward, please make sure you're running Git Bash as Administrator ;)

**Comment by PaulStAmand** [comment]
Ok, thanks, Might I also suggest looking at ionic and gantry to see how
those packages resolved this on windows. Running as admin isn't ideal.

I think I tried as admin, but I'll verify that.

**Comment by PaulStAmand** [comment]
I've updated npm, cache clean, and reinstalled deepify, which now completes

Got a little further

user@toshiba MINGW64 ~
$ deepify server deep-hello-world -o
11:16:53 GMT-0500 (Eastern Standard Time)  { [ValidationError: child "appName" fails because ["appName" is required]]
  name: 'ValidationError',
  details:
   [ { message: '"appName" is required',
       path: 'appName',
       type: 'any.required',
       context: [Object] } ],
  _object:
   { appIdentifier: 'unique-app-id-1456596859557',
     env: 'dev',
     awsAccountId: 123456789012,
     aws: { accessKeyId: '', secretAccessKey: '', region: 'us-east-1' } },
  annotate: [Function] }
11:16:53 GMT-0500 (Eastern Standard Time)  b: ValidationError: child "appName" fails because ["appName" is required]
    at a._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-package-manager\lib.compiled\Property\Config.js:1:1191)
    at new a (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-package-manager\lib.compiled\Property\Instance.js:1:2834)
    at a.module.exports [as _action] (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\commands\server.js:51:18)
    at a._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Terminal\Program.js:1:4333)
    at a._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Terminal\Program.js:1:4087)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\deepify.js:56:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by PaulStAmand** [comment]
On the windows 7 machine with git bash as admin

user@user-3 MINGW64 ~
$ pwd
/c/Users/user

user@user-3 MINGW64 ~
$ npm cache clean

user@user-3 MINGW64 ~
$ npm update npm -g

user@user-3 MINGW64 ~
$ npm cache clean

user@user-3 MINGW64 ~
$ npm install deepify -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "deepify" "-g"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\com
mands
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\user\AppData\Roamin
g\npm\node_modules\deepify\bin\commands'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, rmdir 'C:\Use
rs\user\AppData\Roaming\npm\node_modules\deepify\bin\commands'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'C:
\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\commands']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: 'C:\\Users\\user\\AppData\\Roaming\\npm\
\node_modules\\deepify\\bin\\commands' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

user@user-3 MINGW64 ~
$

**Comment by eistrati** [comment]
@PaulStAmand We have recently introduced this new parameter `appNameas required, so older versions of the software fails. I apologize for this oversight, but we're working now to fix this issue by default. As a work-around, please delete `deeploy.json`

**Comment by eistrati** [comment]
@PaulStAmand It looks like this is a known issue and we'll keep monitoring it as well: https://github.com/npm/npm/issues/7370 (some people suggest reboot, others npm cache clean; at this point we're dependent by `npm` functionality and unfortunately we can't make any fixes).

**Comment by eistrati** [comment]
Quick update: the `appName` issue was fixed. Please rerun `npm install deepify -g` to get the updated libraries. Again, sorry for this oversight, should be ok now.

**Comment by PaulStAmand** [comment]
ok from CMD I'm prompted for  entry when launching deepify server deep-hello-world
but from git-bash the prompt is being redirected somewhere else.

if I hit return enough times under git-bash I get to this point

user@toshiba MINGW64 ~
$ deepify server /c/users/user/deep-hello-world












16:03:25 GMT-0500 (Eastern Standard Time)  No init hook found for microservice hello.world.example
16:03:25 GMT-0500 (Eastern Standard Time)  Running init hook for microservice deep.ng.root
16:03:25 GMT-0500 (Eastern Standard Time)  No init hook found for microservice hello.world.example

Installing latest deep-framework from GitHub
######################################################################## 100.0%
16:03:27 GMT-0500 (Eastern Standard Time)  Running "npm install" on 2 Lambdas
npm WARN package.json say-hello-world@0.0.1 No README data
npm WARN package.json say-hello-world@0.0.1 No README data

> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-validation\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js


> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-validation\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js





















npm ERR! tar.pack Could not write C:\Users\user\AppData\Roaming\npm-cache\local-dynamo\0.1.2\package.tgz
npm ERR! addLocalDirectory Could not pack C:\Users\user\AppData\Local\Temp\npm-5804-f966608c\git-cache-23a1963e4cf2\4dad4edb3dea1a3d1d1834df07b2e4a4d8946b74 to C:\Users\user\AppData\Roaming\npm-cache\local-dynamo\0.1.2\package.tgz
npm ERR! addLocal Could not install C:\Users\user\AppData\Local\Temp\npm-5804-f966608c\git-cache-23a1963e4cf2\4dad4edb3dea1a3d1d1834df07b2e4a4d8946b74

> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js



















































> leveldown@1.4.4 install C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\dynalite\node_modules\leveldown
> prebuild --install


> say-hello-world@0.0.1 postinstall C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello
> npm run compile


> say-hello-world@0.0.1 compile C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello
> deepify compile-es6 `pwd`


> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

deep-framework@1.8.5 node_modules\deep-framework
├── inherits@2.0.1
├── deep-notification@1.7.0
├── deep-event@1.7.0
├── deep-asset@1.7.0
├── deep-di@1.7.0 (bottlejs@1.2.2)
├── deep-kernel@1.7.0 (wait-until@0.0.2)
├── deep-core@1.7.2 (qs@5.2.0)
├── deep-cache@1.7.0 (store@1.3.20, ecad@0.2.0, ioredis@1.15.1)
├── deep-log@1.7.1 (raven@0.7.3, joi@5.1.0, aws-sdk@2.2.41)
├── deep-resource@1.7.1 (qs@5.2.0, aws4@1.1.0, url-parse@1.0.5, superagent@1.7.2, aws-sdk@2.2.41)
├── deep-fs@1.7.1 (relative-fs@0.0.1, es6-promise@3.1.2, fs-extra@0.26.5, s3fs@2.4.0)
├── deep-security@1.7.1 (amazon-cognito-js@1.0.0, aws-sdk@2.2.41)
├── deep-validation@1.7.1 (joi@5.1.0, vogels@2.2.0)
└── deep-db@1.7.0 (fs-extra@0.26.5, joi@5.1.0, local-dynamo@0.1.2, vogels@2.2.0, dynalite@0.17.3)

> leveldown@1.4.4 install C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\dynalite\node_modules\leveldown
> prebuild --install


> say-hello-world@0.0.1 postinstall C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello
> npm run compile


> say-hello-world@0.0.1 compile C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello
> deepify compile-es6 `pwd`

deep-framework@1.8.5 node_modules\deep-framework
├── inherits@2.0.1
├── deep-notification@1.7.0
├── deep-event@1.7.0
├── deep-asset@1.7.0
├── deep-di@1.7.0 (bottlejs@1.2.2)
├── deep-kernel@1.7.0 (wait-until@0.0.2)
├── deep-core@1.7.2 (qs@5.2.0)
├── deep-cache@1.7.0 (store@1.3.20, ecad@0.2.0, ioredis@1.15.1)
├── deep-log@1.7.1 (raven@0.7.3, joi@5.1.0, aws-sdk@2.2.41)
├── deep-resource@1.7.1 (qs@5.2.0, aws4@1.1.0, url-parse@1.0.5, superagent@1.7.2, aws-sdk@2.2.41)
├── deep-fs@1.7.1 (relative-fs@0.0.1, es6-promise@3.1.2, fs-extra@0.26.5, s3fs@2.4.0)
├── deep-security@1.7.1 (amazon-cognito-js@1.0.0, aws-sdk@2.2.41)
├── deep-validation@1.7.1 (joi@5.1.0, vogels@2.2.0)
└── deep-db@1.7.0 (fs-extra@0.26.5, joi@5.1.0, local-dynamo@0.1.2, vogels@2.2.0, dynalite@0.17.3)
16:10:28 GMT-0500 (Eastern Standard Time)  Start linking aws-sdk
aws-sdk@2.2.41 ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk
├── sax@1.1.5
├── xml2js@0.4.15
└── xmlbuilder@2.6.2 (lodash@3.5.0)
C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\aws-sdk -> ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk -> C:\Users\user\AppData\Roaming\npm\node_modules\aws-sdk
aws-sdk@2.2.41 ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk
├── sax@1.1.5
├── xml2js@0.4.15
└── xmlbuilder@2.6.2 (lodash@3.5.0)
C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\aws-sdk -> ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk -> C:\Users\user\AppData\Roaming\npm\node_modules\aws-sdk
16:11:02 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in hello.world.example
16:11:02 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in deep.ng.root
16:11:02 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in hello.world.example
16:11:02 GMT-0500 (Eastern Standard Time)  Booting local FS
16:11:02 GMT-0500 (Eastern Standard Time)  Linking custom validation schemas
16:11:02 GMT-0500 (Eastern Standard Time)  Creating server on port 8000
16:11:02 GMT-0500 (Eastern Standard Time)  HTTP Server is up and running!
16:11:02 GMT-0500 (Eastern Standard Time)  Creating local DynamoDB instance on port 8877
16:11:07 GMT-0500 (Eastern Standard Time)  You can access DynamoDB Console via http://localhost:8877/shell
16:11:07 GMT-0500 (Eastern Standard Time)  No "server after init hook" found in hello.world.example
16:11:07 GMT-0500 (Eastern Standard Time)  No "server after init hook" found in deep.ng.root
16:11:07 GMT-0500 (Eastern Standard Time)  No "server after init hook" found in hello.world.example

**Comment by PaulStAmand** [comment]
DEEP Microservice: Hello World


MyName
  Send
null

**Comment by PaulStAmand** [comment]
user@toshiba MINGW64 ~
$ deepify server /c/users/user/deep-hello-world












16:03:25 GMT-0500 (Eastern Standard Time)  No init hook found for microservice hello.world.example
16:03:25 GMT-0500 (Eastern Standard Time)  Running init hook for microservice deep.ng.root
16:03:25 GMT-0500 (Eastern Standard Time)  No init hook found for microservice hello.world.example

Installing latest deep-framework from GitHub
######################################################################## 100.0%
16:03:27 GMT-0500 (Eastern Standard Time)  Running "npm install" on 2 Lambdas
npm WARN package.json say-hello-world@0.0.1 No README data
npm WARN package.json say-hello-world@0.0.1 No README data

> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-validation\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js


> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-validation\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js





















npm ERR! tar.pack Could not write C:\Users\user\AppData\Roaming\npm-cache\local-dynamo\0.1.2\package.tgz
npm ERR! addLocalDirectory Could not pack C:\Users\user\AppData\Local\Temp\npm-5804-f966608c\git-cache-23a1963e4cf2\4dad4edb3dea1a3d1d1834df07b2e4a4d8946b74 to C:\Users\user\AppData\Roaming\npm-cache\local-dynamo\0.1.2\package.tgz
npm ERR! addLocal Could not install C:\Users\user\AppData\Local\Temp\npm-5804-f966608c\git-cache-23a1963e4cf2\4dad4edb3dea1a3d1d1834df07b2e4a4d8946b74

> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js



















































> leveldown@1.4.4 install C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\dynalite\node_modules\leveldown
> prebuild --install


> say-hello-world@0.0.1 postinstall C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello
> npm run compile


> say-hello-world@0.0.1 compile C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello
> deepify compile-es6 `pwd`


> dtrace-provider@0.6.0 install C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

deep-framework@1.8.5 node_modules\deep-framework
├── inherits@2.0.1
├── deep-notification@1.7.0
├── deep-event@1.7.0
├── deep-asset@1.7.0
├── deep-di@1.7.0 (bottlejs@1.2.2)
├── deep-kernel@1.7.0 (wait-until@0.0.2)
├── deep-core@1.7.2 (qs@5.2.0)
├── deep-cache@1.7.0 (store@1.3.20, ecad@0.2.0, ioredis@1.15.1)
├── deep-log@1.7.1 (raven@0.7.3, joi@5.1.0, aws-sdk@2.2.41)
├── deep-resource@1.7.1 (qs@5.2.0, aws4@1.1.0, url-parse@1.0.5, superagent@1.7.2, aws-sdk@2.2.41)
├── deep-fs@1.7.1 (relative-fs@0.0.1, es6-promise@3.1.2, fs-extra@0.26.5, s3fs@2.4.0)
├── deep-security@1.7.1 (amazon-cognito-js@1.0.0, aws-sdk@2.2.41)
├── deep-validation@1.7.1 (joi@5.1.0, vogels@2.2.0)
└── deep-db@1.7.0 (fs-extra@0.26.5, joi@5.1.0, local-dynamo@0.1.2, vogels@2.2.0, dynalite@0.17.3)

> leveldown@1.4.4 install C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\deep-framework\node_modules\deep-db\node_modules\dynalite\node_modules\leveldown
> prebuild --install


> say-hello-world@0.0.1 postinstall C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello
> npm run compile


> say-hello-world@0.0.1 compile C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello
> deepify compile-es6 `pwd`

deep-framework@1.8.5 node_modules\deep-framework
├── inherits@2.0.1
├── deep-notification@1.7.0
├── deep-event@1.7.0
├── deep-asset@1.7.0
├── deep-di@1.7.0 (bottlejs@1.2.2)
├── deep-kernel@1.7.0 (wait-until@0.0.2)
├── deep-core@1.7.2 (qs@5.2.0)
├── deep-cache@1.7.0 (store@1.3.20, ecad@0.2.0, ioredis@1.15.1)
├── deep-log@1.7.1 (raven@0.7.3, joi@5.1.0, aws-sdk@2.2.41)
├── deep-resource@1.7.1 (qs@5.2.0, aws4@1.1.0, url-parse@1.0.5, superagent@1.7.2, aws-sdk@2.2.41)
├── deep-fs@1.7.1 (relative-fs@0.0.1, es6-promise@3.1.2, fs-extra@0.26.5, s3fs@2.4.0)
├── deep-security@1.7.1 (amazon-cognito-js@1.0.0, aws-sdk@2.2.41)
├── deep-validation@1.7.1 (joi@5.1.0, vogels@2.2.0)
└── deep-db@1.7.0 (fs-extra@0.26.5, joi@5.1.0, local-dynamo@0.1.2, vogels@2.2.0, dynalite@0.17.3)
16:10:28 GMT-0500 (Eastern Standard Time)  Start linking aws-sdk
aws-sdk@2.2.41 ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk
├── sax@1.1.5
├── xml2js@0.4.15
└── xmlbuilder@2.6.2 (lodash@3.5.0)
C:\users\user\deep-hello-world\DeepHelloWorld\Backend\src\SayHello\node_modules\aws-sdk -> ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk -> C:\Users\user\AppData\Roaming\npm\node_modules\aws-sdk
aws-sdk@2.2.41 ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk
├── sax@1.1.5
├── xml2js@0.4.15
└── xmlbuilder@2.6.2 (lodash@3.5.0)
C:\users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\aws-sdk -> ..\..\..\..\..\AppData\Roaming\npm\node_modules\aws-sdk -> C:\Users\user\AppData\Roaming\npm\node_modules\aws-sdk
16:11:02 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in hello.world.example
16:11:02 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in deep.ng.root
16:11:02 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in hello.world.example
16:11:02 GMT-0500 (Eastern Standard Time)  Booting local FS
16:11:02 GMT-0500 (Eastern Standard Time)  Linking custom validation schemas
16:11:02 GMT-0500 (Eastern Standard Time)  Creating server on port 8000
16:11:02 GMT-0500 (Eastern Standard Time)  HTTP Server is up and running!
16:11:02 GMT-0500 (Eastern Standard Time)  Creating local DynamoDB instance on port 8877
16:11:07 GMT-0500 (Eastern Standard Time)  You can access DynamoDB Console via http://localhost:8877/shell
16:11:07 GMT-0500 (Eastern Standard Time)  No "server after init hook" found in hello.world.example
16:11:07 GMT-0500 (Eastern Standard Time)  No "server after init hook" found in deep.ng.root
16:11:07 GMT-0500 (Eastern Standard Time)  No "server after init hook" found in hello.world.example

16:13:52 GMT-0500 (Eastern Standard Time)  Request / -> /
16:13:52 GMT-0500 (Eastern Standard Time)  Resolving C:\users\user\deep-hello-world\deep.ng.root\Frontend into C:\users\user\deep-hello-world\deep.ng.root\Frontend/index.html
16:13:52 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\index.html of type text/html
16:13:52 GMT-0500 (Eastern Standard Time)  Request /js/lib/deep-framework.js -> /js/lib/deep-framework.js
16:13:52 GMT-0500 (Eastern Standard Time)  Request /js/lib/traceur.min.js -> /js/lib/traceur.min.js
16:13:52 GMT-0500 (Eastern Standard Time)  Request /bootstrap.js -> /bootstrap.js
16:13:52 GMT-0500 (Eastern Standard Time)  Request /js/lib/system.js -> /js/lib/system.js
16:13:52 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\bootstrap.js of type application/javascript
16:13:52 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\lib\system.js of type application/javascript
16:13:52 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\lib\traceur.min.js of type application/javascript
16:13:53 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\lib\deep-framework.js of type application/javascript
16:14:00 GMT-0500 (Eastern Standard Time)  Request /_config.json -> /_config.json
16:14:00 GMT-0500 (Eastern Standard Time)  Request /img/favicon.ico -> /img/favicon.ico
16:14:00 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\img\favicon.ico of type image/x-icon
16:14:00 GMT-0500 (Eastern Standard Time)  Request /__deep_validation_schemas__/NameData.js -> /__deep_validation_schemas__/NameData.js
16:14:00 GMT-0500 (Eastern Standard Time)  {LFS} /__deep_validation_schemas__/NameData.js resolved into C:\Users\user\AppData\Local\Temp\598856086c90c6c19e561b6fcb3653a0-public\__deep_validation_schemas__\NameData.js
16:14:00 GMT-0500 (Eastern Standard Time)  Serving file C:\Users\user\AppData\Local\Temp\598856086c90c6c19e561b6fcb3653a0-public\__deep_validation_schemas__\NameData.js of type application/javascript
16:14:00 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/bootstrap.js?_v=52b3b607.js -> /hello.world.example/bootstrap.js
16:14:00 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\bootstrap.js of type application/javascript
16:14:00 GMT-0500 (Eastern Standard Time)  Request /js/lib/css.js -> /js/lib/css.js
16:14:00 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\lib\css.js of type application/javascript
16:14:00 GMT-0500 (Eastern Standard Time)  Request /js/lib/angular.js -> /js/lib/angular.js
16:14:01 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\lib\angular.js of type application/javascript
16:14:04 GMT-0500 (Eastern Standard Time)  Request /js/lib/angular-ui-router.js -> /js/lib/angular-ui-router.js
16:14:04 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\lib\angular-ui-router.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/index.js -> /hello.world.example/js/app/angular/index.js
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\index.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/name.js -> /hello.world.example/js/app/angular/name.js
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/module/index.js -> /hello.world.example/js/app/angular/module/index.js
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/controllers/index.js -> /hello.world.example/js/app/angular/controllers/index.js
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\name.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\controllers\index.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\module\index.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/module/ng-config.js -> /hello.world.example/js/app/angular/module/ng-config.js
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/module/ng-module.js -> /hello.world.example/js/app/angular/module/ng-module.js
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/module/ng-run.js -> /hello.world.example/js/app/angular/module/ng-run.js
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\module\ng-module.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\module\ng-run.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\module\ng-config.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/module/ng-routes.js -> /hello.world.example/js/app/angular/module/ng-routes.js
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\module\ng-routes.js of type application/javascript
16:14:05 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/controllers/SayHelloController.js -> /hello.world.example/js/app/angular/controllers/SayHelloController.js
16:14:05 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\controllers\SayHelloController.js of type application/javascript
16:14:06 GMT-0500 (Eastern Standard Time)  Request /js/app/module/index.js -> /js/app/module/index.js
16:14:06 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\app\module\index.js of type application/javascript
16:14:06 GMT-0500 (Eastern Standard Time)  Request /js/app/module/ng-module.js -> /js/app/module/ng-module.js
16:14:06 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\app\module\ng-module.js of type application/javascript
16:14:06 GMT-0500 (Eastern Standard Time)  Request /js/app/name.js -> /js/app/name.js
16:14:06 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\app\name.js of type application/javascript
16:14:06 GMT-0500 (Eastern Standard Time)  Request /js/app/index.js -> /js/app/index.js
16:14:06 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\app\index.js of type application/javascript
16:14:06 GMT-0500 (Eastern Standard Time)  Request /js/app/directives/index.js -> /js/app/directives/index.js
16:14:06 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\app\directives\index.js of type application/javascript
16:14:06 GMT-0500 (Eastern Standard Time)  Request /js/app/directives/updateTitle.js -> /js/app/directives/updateTitle.js
16:14:06 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\deep.ng.root\Frontend\js\app\directives\updateTitle.js of type application/javascript
16:14:06 GMT-0500 (Eastern Standard Time)  Request /hello.world.example/js/app/angular/views/hello.html?_v=52b3b607 -> /hello.world.example/js/app/angular/views/hello.html
16:14:06 GMT-0500 (Eastern Standard Time)  Serving file C:\users\user\deep-hello-world\DeepHelloWorld\Frontend\js\app\angular\views\hello.html of type text/html
16:14:15 GMT-0500 (Eastern Standard Time)  Request /_/lambda -> /_/lambda
16:14:15 GMT-0500 (Eastern Standard Time)  Running Lambda arn:aws:lambda:::function:hello.world.example-sample-say-hello with payload {"Name":"MyName"}
16:14:42 GMT-0500 (Eastern Standard Time)  Lambda hello.world.example-sample-say-hello execution fail undefined
16:14:42 GMT-0500 (Eastern Standard Time)  Serving result for Lambda hello.world.example-sample-say-hello: "{\"errorType\":\"Error\",\"errorMessage\":\"ENOENT: no such file or directory, open 'C:\\\\Users\\\\user\\\\AppData\\\\Local\\\\Temp\\\\598856086c90c6c19e561b6fcb3653a0-system\\\\hello.world.example\\\\system\\\\request_payload_2016-03-04T21:14:42.349Z'\",\"errorStack\":\"Error: ENOENT: no such file or directory, open 'C:\\\\Users\\\\user\\\\AppData\\\\Local\\\\Temp\\\\598856086c90c6c19e561b6fcb3653a0-system\\\\hello.world.example\\\\system\\\\request_payload_2016-03-04T21:14:42.349Z'\\n    at Error (native)\",\"_deep_error_code_\":500}"
Timing for hello.world.example-sample-say-hello-0: 3.21 seconds

**Comment by eistrati** [comment]
Ok, we're really close, almost there :) I've acknowledged this issue and we'll get back to you asap.

**Comment by PaulStAmand** [comment]
I tried deleting the deep-hello-world to just get a clean start and there may be a pathing issue or modules being installed into subfolders

C:\Users\user\DEEP-H~1\DEEP-M~1\Backend\src\SayHello\NODE_M~1\DEEP-F~1\NODE_M~1\deep-db\NODE_M~1\dynalite\NODE_M~1\LEVELD~1\NODE_M~1\prebuild\NODE_M~1\GHRELE~1\NODE_M~1\ghutils\NODE_M~1\jsonist\NODE_M~1\HYPERQ~1\NODE_M~1\through2\NODE_M~1\readable-stream

**Comment by eistrati** [comment]
@PaulStAmand Sorry for delay on our end. Using Git Bash, run the following command: `rm -rf C:\users\user\deep-hello-world`. This should take care of everything.

Next, reinstall deepify and hello-world: `npm install deepify -g` and `deepify helloworld ./deep-hello-world`. Please let me know if you still have issues running `deepify server`.

**Comment by PaulStAmand** [comment]
Removed and reinstalled deep if and the helloworld.

Install from git bash

If I run server from git bash I don't get any of the prompts

I can continue to hit return so the input request takes and it will finally
get to the same point the cmd gets to

Serving file...

I see them and can accept all the defaults and it Launches from cmd

I notice after type your name and hitting send under Windows and aws linux
an additional line with

null no longer appears

After a humber of seconds

A json output appears below the text entry field.

The server windows says <2 seconds , there must be local npm init on
getting the local lambda env ready, it takes almost 20 seconds before the
front end changes,

Occasionally, null still appears but it's not every time.

**Comment by eistrati** [comment]
Ok, much better now :) Looks like prompt is not working properly on Windows. We didn't have such issues, but I remember you've mentioned it with other occasions, so we'll check.

Yes, unfortunately the performance of "Lambda" on localhost is slow. We have this issue on our radar, but it's not critical since you can see in logs the response time of 20 seconds (on my machine it's 15 seconds). When you deploy on AWS, it's MUCH faster and we'll continue improving it ;)

Please feel free to let us know of any other issue you come across (and maybe in a separate ticket:) I'll close this ticket for now and will open separate ones that are strictly related to `npm` issues on Windows.

Thanks, @PaulStAmand!
